# Generated by Django 3.1.7 on 2021-06-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210526_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_image',
            field=models.BooleanField(default=True),
        ),
    ]
