# Generated by Django 3.1.7 on 2021-06-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_is_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_image',
        ),
    ]
