# Generated by Django 3.1.7 on 2021-06-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_is_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_option', models.CharField(default='', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Option_Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_option', models.CharField(default='', max_length=100)),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_option')),
            ],
        ),
    ]
