# Generated by Django 3.1.7 on 2021-06-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_address_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='selected',
            new_name='default',
        ),
    ]
