# Generated by Django 3.1.7 on 2021-06-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
