# Generated by Django 3.1.7 on 2021-05-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='create_at',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
