# Generated by Django 3.1.7 on 2021-06-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210602_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_rating',
            field=models.BooleanField(default=False),
        ),
    ]
